config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{comment.tweet.id}"
  end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
  end

  def create
      Tweet.create(image: tweet_params[:image], text: tweet_params[:text], user_id: current_user.id)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update(tweet_params)
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.includes(:user)
  end

  private
  def tweet_params
      params.permit(:image, :text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appmini</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
   <header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/">The World of Aphorism</a></h1>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <a href="/users/<%= current_user.id %>">My page</a>
                <%= link_to "Log-out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <a class="post" href="/tweets/new">submit</a>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "Log-in", new_user_session_path, :class => 'post' %>
          <%= link_to "sign-up", new_user_registration_path, :class => 'post' %>
        </div>
      <% end %>
    </div>
  </header>

    <%= yield %>

        <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Aphorism</h5>
                <p class="grey-text text-lighten-4">An aphorism is a concise, terse, laconic, and/or memorable expression of a general truth or principle.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            Copyright PicTweet 2014.
            <a class="grey-text text-lighten-4 right" href="#!">You can do it!</a>
            </div>
          </div>
        </footer>
      <p>
        by Tatsuya Kitamura
      </p>
    </footer>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);">
  <div class="more">
    <span><%= image_tag 'arrow_top.png' %></span>
    <ul class="more_list">
      <li>
        <%= link_to "detail", tweet_path(tweet.id), method: :get %>
      </li>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li>
          <%= link_to 'edit', "/tweets/#{tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to 'delete', "/tweets/#{tweet.id}", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
  <%= simple_format(tweet.text) %>
  <span class="name">
    <a href="/users/<%= tweet.user_id %>">
      <span>contributer</span><%= tweet.user.nickname %>
    </a>
  </span>
</div>

app/views/tweets/create.html.erb
<div class="contents detail">
  <p>--------------------------------------------------------------</p>
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="http://livedoor.blogimg.jp/tomov808/imgs/9/d/9de53650.jpg">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">ありがとうございました<i class="material-icons right"></i></span>
      <p><a href="#">またよろしくお願いします。</a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Thank you for using.<i class="material-icons right"></i></span>
    </div>
  </div>
</div class="contents detail">
<div class="contents row">
  <div class="success">
    <h3>
      success of submit
    </h3>
    <a class="btn" href="/tweets">return to index</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents detail">
  <p>--------------------------------------------------------------</p>
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="http://livedoor.blogimg.jp/tomov808/imgs/9/d/9de53650.jpg">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">ありがとうございました<i class="material-icons right"></i></span>
      <p><a href="#">またよろしくお願いします。</a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Thank you for using.<i class="material-icons right"></i></span>
    </div>
  </div>
</div class="contents detail">
<div class="contents row">
  <div class="success">
    <h3>
      success of delete
    </h3>
    <a class="btn" href="/">return to index</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents detail">
  <p>--------------------------------------------------------------</p>
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="http://livedoor.blogimg.jp/tomov808/imgs/9/d/9de53650.jpg">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">よろしくお願いします<i class="material-icons right"></i></span>
      <p><a href="#">面白い言葉をお待ちしております。</a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Thank you for preparing.<i class="material-icons right"></i></span>
    </div>
  </div>
</div class="contents detail">
<div class="contents row">
  <%= form_tag("/tweets/#{@tweet.id}", method: :patch ) do %>
    <h3>
      starting to edit
    </h3>
    <input placeholder="Image Url" type="text" name="image" value="<%= @tweet.image %>" autofocus="true">
    <textarea cols="30" name="text" placeholder="text" rows="10"><%= @tweet.text %></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

app/views/tweets/index.html.erb
  <div class="contents detail">
      <div class="text">ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー</div>
      <div class="text">＜＜Aphorismとは＞＞</div>
      <div class="row">
        <div class="col s12 m7">
          <div class="card">
            <div class="card-image">
              <img src="https://pbs.twimg.com/profile_images/378800000078254412/95765c985e288bd1a08930eee9dc208b_400x400.jpeg">
              <span class="card-title">犬の一言</span>
            </div>
            <div class="card-content">
              <p>と、名言を言っています。</p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
            </div>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="https://lohas.nicoseiga.jp/thumb/7814469i?1516461385">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">by ルパン三世<i class="material-icons right"></i></span>
          <p><a href="#">This is a link</a></p>
        </div>
      </div>
      <div class="row">
        <div class="col s12 m6">
          <div class="card">
            <div class="card-image">
              <img src="https://static.curazy.com/wp-content/uploads/2017/10/3074510_ru-ru-600x315.jpg">
              <span class="card-title"></span>
              <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons"></i></a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">Card Title</span>
              <p>是非みなさんもご投稿をよろしくお願いします。</p>
              <p>Welcome to the world of aphorism!</p>
              <p>Would you like to submit you impressive aphorism?</p>
              <p>Thank you for coming this page!</p>
            </div>
          </div>
        </div>
      </div>
  </div>
  <div class="contents row">
    <% @tweets.each do |tweet| %>
      <%= render partial: "tweet", locals: { tweet: tweet } %>
    <% end %>
    <%= paginate(@tweets) %>
  </div>

app/views/tweets/new.html.erb
<div class="contents detail">
  <p>--------------------------------------------------------------</p>
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="http://livedoor.blogimg.jp/tomov808/imgs/9/d/9de53650.jpg">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">よろしくお願いします<i class="material-icons right"></i></span>
      <p><a href="#">面白い言葉をお待ちしております。</a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Thank you for preparing.<i class="material-icons right"></i></span>
    </div>
  </div>
</div class="contents detail">
<div class="contents row">
  <div class="container">
  <%= form_with url:"/tweets", method: :post, local: true do |f| %>
    <h3>
      starting to submit
    </h3>
    <%= f.text_field :image, :placeholder=> "Image URL" %>
    <%= f.text_area :text, class: "tweet", size: "30*10", :placeholder=>"text" %>
    <%= f.submit 'submit' %>
  <% end %>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="contents detail">
  <p>--------------------------------------------------------------</p>
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="http://livedoor.blogimg.jp/tomov808/imgs/9/d/9de53650.jpg">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">よろしくお願いします<i class="material-icons right"></i></span>
      <p><a href="#">面白い言葉をお待ちしております。</a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Thank you for preparing.<i class="material-icons right"></i></span>
    </div>
  </div>
</div class="contents detail">
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to 'edit', "/tweets/#{@tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to 'delete', "/tweets/#{@tweet.id}", method: :delete %>
        </li>
      </ul>
    </div>
    <% end %>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>contributer</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <!-- ここからフォーム -->
    <% if current_user %>
      <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
        <textarea cols="30" name="text" placeholder="starting to comment" rows="2"></textarea>
        <input type="submit" value="SENT">
      <% end %>
    <% end %>
    <div class="comments">
      <h4>＜index of comments＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
<div class="contents detail">
  <p>--------------------------------------------------------------</p>
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="http://livedoor.blogimg.jp/tomov808/imgs/9/d/9de53650.jpg">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">ありがとうございました<i class="material-icons right"></i></span>
      <p><a href="#">またよろしくお願いします。</a></p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Thank you for updating.<i class="material-icons right"></i></span>
    </div>
  </div>
</div class="contents detail">
<div class="contents row">
  <div class="success">
    <h3>
      success updating
    </h3>
    <a class="btn" href="/">return to index</a>
   </div>
</div>

app/views/users/show.html.erb
<div class="contents detail">
  <div class="text">ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー</div>
  <div class="text">＜＜Aphorismとは＞＞</div>
  <div class="row">
    <div class="col s12 m7">
      <div class="card">
        <div class="card-image">
          <img src="https://pbs.twimg.com/profile_images/378800000078254412/95765c985e288bd1a08930eee9dc208b_400x400.jpeg">
          <span class="card-title">犬の一言</span>
        </div>
        <div class="card-content">
          <p>と、名言を言っています。</p>
        </div>
        <div class="card-action">
          <a href="#">This is a link</a>
        </div>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="https://lohas.nicoseiga.jp/thumb/7814469i?1516461385">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">by ルパン三世<i class="material-icons right"></i></span>
      <p><a href="#">This is a link</a></p>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m6">
      <div class="card">
        <div class="card-image">
          <img src="https://static.curazy.com/wp-content/uploads/2017/10/3074510_ru-ru-600x315.jpg">
          <span class="card-title"></span>
          <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="contents row" >
  <p><%= @nickname %>'s index</p>
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
  <% end %>
  <%= paginate(@tweets) %>
</div>